// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdBOZJ7trV8UC_7bXnR4NBWhiLhva-yMo',
    appId: '1:41351914272:web:ed4376311622238b3ced45',
    messagingSenderId: '41351914272',
    projectId: 'passgen-36951',
    authDomain: 'passgen-36951.firebaseapp.com',
    storageBucket: 'passgen-36951.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn9-BjzgE1a4g86JC4AO3rbawrW2oCM1c',
    appId: '1:41351914272:android:4a837b288886fd143ced45',
    messagingSenderId: '41351914272',
    projectId: 'passgen-36951',
    storageBucket: 'passgen-36951.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB3GXRSfU9mAkWEnbJ_UTEK8tDFvUW0No',
    appId: '1:41351914272:ios:e6e13faa908dd61f3ced45',
    messagingSenderId: '41351914272',
    projectId: 'passgen-36951',
    storageBucket: 'passgen-36951.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB3GXRSfU9mAkWEnbJ_UTEK8tDFvUW0No',
    appId: '1:41351914272:ios:720b51b2ee8034863ced45',
    messagingSenderId: '41351914272',
    projectId: 'passgen-36951',
    storageBucket: 'passgen-36951.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
